/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_LoadingNativeCode_LoadingNativeCode */

#ifndef _Included_com_LoadingNativeCode_LoadingNativeCode
#define _Included_com_LoadingNativeCode_LoadingNativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_LoadingNativeCode_LoadingNativeCode
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT int JNICALL Java_com_LoadingNativeCode_LoadingNativeCode_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
